// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaOrcamentario.Context;

#nullable disable

namespace SistemaOrcamentario.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230407160318_correcaoMappings")]
    partial class correcaoMappings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaOrcamentario.Models.OrcamentoModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("PessoaID")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaModelID")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoEntrega")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("varchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("PessoaID");

                    b.HasIndex("PessoaModelID");

                    b.ToTable("Orcamento", (string)null);
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.PessoaModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NumberCellPhone")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NumberFixPhone")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID");

                    b.ToTable("Pessoa", (string)null);
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.OrcamentoModel", b =>
                {
                    b.HasOne("SistemaOrcamentario.Models.PessoaModel", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaOrcamentario.Models.PessoaModel", null)
                        .WithMany("Orcamentos")
                        .HasForeignKey("PessoaModelID");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.PessoaModel", b =>
                {
                    b.Navigation("Orcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
