// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaOrcamentario.Context;

#nullable disable

namespace SistemaOrcamentario.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231114141359_Organizacao.TabelasApp001")]
    partial class OrganizacaoTabelasApp001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaOrcamentario.Models.OrcamentoModel", b =>
                {
                    b.Property<int>("OrcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcId"));

                    b.Property<string>("OrcDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrcIncEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrcObservacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrcPreco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrcTipoEntrega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrcTipoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrcamentoPessoaPesId")
                        .HasColumnType("int");

                    b.Property<int>("PesId")
                        .HasColumnType("int");

                    b.HasKey("OrcId");

                    b.HasIndex("OrcamentoPessoaPesId");

                    b.ToTable("TBORCAMENTO");
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.PessoaModel", b =>
                {
                    b.Property<int>("PesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PesId"));

                    b.Property<string>("PesBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesCep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesCpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PesIncEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PesNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesNumCelular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesNumTelefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesNumero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesRua")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PesId");

                    b.ToTable("TBPESSOA");
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.UsuarioModel", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuId"));

                    b.Property<DateTime?>("UsuAltEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsuIncEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuPerfil")
                        .HasColumnType("int");

                    b.Property<string>("UsuSenha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuId");

                    b.ToTable("TBUSUARIO");
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.OrcamentoModel", b =>
                {
                    b.HasOne("SistemaOrcamentario.Models.PessoaModel", "OrcamentoPessoa")
                        .WithMany("Orcamentos")
                        .HasForeignKey("OrcamentoPessoaPesId");

                    b.Navigation("OrcamentoPessoa");
                });

            modelBuilder.Entity("SistemaOrcamentario.Models.PessoaModel", b =>
                {
                    b.Navigation("Orcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
